version: '3'

services:
  backend_device_manager:
    container_name: 'backend_device_manager'
    build: 
      context: ./backend
    ports:
      - '8000:8000'

  frontend_device_manager:
    container_name: 'frontend_device_manager'
    build: 
      context: ./frontend
    ports:
      - '3000:8080'
